-- MySQL Script generated by MySQL Workbench
-- Wed May 27 22:11:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema applicantdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema applicantdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `applicantdb` DEFAULT CHARACTER SET utf8 ;
USE `applicantdb` ;

-- -----------------------------------------------------
-- Table `applicantdb`.`Applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applicantdb`.`Applicant` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FamilyName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `CountryOfOrigin` VARCHAR(45) NOT NULL,
  `EMailAddress` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Hired` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
